---
### CSP Service ###
kind: Service
apiVersion: v1
metadata:
  name: csp-service
  namespace: kube-system
  labels:
    app: csp-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: csp-service

---
### CSP deployment ###
kind: Deployment
apiVersion: apps/v1
metadata:
  name: csp-service
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csp-service
  replicas: 1
  template:
    metadata:
      labels:
        app: csp-service
    spec:
      containers:
        - name: csp-service
          image: {{ .Values.cspImage}}: {{- .Values.cspTag}}
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          volumeMounts:
            - name: log-dir
              mountPath: /var/log
      volumes:
        - name: log-dir
          hostPath:
            path: /var/log
