---
apiVersion: v1
kind: Secret
metadata:
  name: nimble-secret
  namespace: kube-system
stringData:
  username: {{ .Values.username }}
  password: {{ .Values.password }}
  servicePort: {{ .Values.port | quote }}
  backend: {{ .Values.arrayIp }}
  serviceName: {{ .Values.cspServiceName }}
