#### Kube Storage Controller (Dynamic Provisioner aka doryd) ###
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-storage-controller-doryd
  namespace: kube-system
  labels:
    app: doryd
spec:
  strategy:
     type: RollingUpdate
  template:
    metadata:
      labels:
        daemon: kube-storage-controller-daemon
      name: kube-storage-controller
    spec:
      restartPolicy: Always
      serviceAccountName: hpe-flexvolume-sa
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: dynamic-provisioner
          image: {{ .Values.dynamicProvisionerImage}}: {{- .Values.dynamicProvisionerTag}}
          imagePullPolicy: Always
          name: kube-storage-controller
          volumeMounts:
             - name: k8s
               mountPath: /etc/kubernetes
             - name: flexvolumedriver
               mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
             - name: hpeconfig
               mountPath: /etc/hpe-storage/
             - name: varlog
               mountPath: /var/log
          securityContext:
            privileged: true
      volumes:
        - name: k8s
          hostPath:
             path: /etc/kubernetes/
        - name: flexvolumedriver
          hostPath:
             path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
        - name: hpeconfig
          hostPath:
              path: /etc/hpe-storage/
        - name: varlog
          hostPath:
              path: /var/log