#### HPE Dynamic Provisioner ###
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hpe-dynamic-provisioner
  namespace: kube-system
  labels:
    app: hpe-dynamic-provisioner
spec:
  strategy:
     type: RollingUpdate
  template:
    metadata:
      labels:
        daemon: hpe-dynamic-provisioner-daemon
      name: hpe-dynamic-provisioner
    spec:
      restartPolicy: Always
      serviceAccountName: hpe-flexvolume-sa
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        -
          image: {{ .Values.dynamicProvisionerImage}}: {{- .Values.dynamicProvisionerTag}}
          imagePullPolicy: Always
          name: hpe-dynamic-provisioner
          volumeMounts:
             - name: k8s
               mountPath: /etc/kubernetes
             - name: flexvolumedriver
               mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
             - name: hpeconfig
               mountPath: /etc/hpe-storage
             - name: varlog
               mountPath: /var/log
          securityContext:
            privileged: true
      volumes:
        - name: k8s
          hostPath:
             path: /etc/kubernetes
        - name: flexvolumedriver
          hostPath:
             path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
        - name: hpeconfig
          hostPath:
              path: /etc/hpe-storage
        - name: varlog
          hostPath:
              path: /var/log