---
apiVersion: v1
kind: Secret
metadata:
  name: nimble-secret
  namespace: kube-system
stringData:
  username: {{ .Values.username }}
  password: {{ .Values.password }}
  arrayIp: {{ .Values.arrayIp }}
  protocol: {{ .Values.protocol }}
